#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
#. Print the numpy version and the configuration
print("Version",np.__version__)
print(np.show_config())

Version 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cy

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
#Create a null vector of size 10
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr=np.array(["1","2","3"],dtype=int)
for i in arr:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
#How to find the memory size of any array
array=np.array([1,2,3])
print(array.dtype)

int64


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array=np.zeros(10)
array[4]=1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array=np.array(range(10,50))
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array=np.arange(1,11)
print(array)
reverse=array[::-1]
print(reverse)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array = np.array([1, 2, 0, 0, 4, 0])

non_zero_indices = np.nonzero(array)[0]
print(non_zero_indices)

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
matrix=np.random.rand(3,3)
print(matrix)

[[0.26453404 0.37550428 0.07266693]
 [0.15243241 0.61454533 0.97894051]
 [0.09628245 0.54419838 0.24820959]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr=np.random.rand(10,10)
min_value=np.min(arr)
max_value=np.max(arr)
print("Min_Value=",min_value)
print("Max_Value=",max_value)
print(arr)

Min_Value= 0.013786642000760185
Max_Value= 0.9843286736891526
[[0.88980285 0.53942113 0.34988774 0.64873243 0.44675055 0.95495615
  0.91272195 0.44740462 0.39830292 0.15380409]
 [0.17404814 0.27187497 0.55867147 0.50479077 0.3204373  0.85339823
  0.62672753 0.21756243 0.94971822 0.64741164]
 [0.8294808  0.66186799 0.0281789  0.55653144 0.06163387 0.01378664
  0.51911143 0.4500179  0.79673107 0.08470087]
 [0.35717167 0.55141689 0.33179157 0.93113172 0.59590787 0.73805152
  0.39437012 0.14889191 0.74348171 0.66082476]
 [0.41658994 0.53651334 0.28195907 0.28128927 0.50942956 0.4973675
  0.54573275 0.70071575 0.5410146  0.33197226]
 [0.58289182 0.02477223 0.31166391 0.65799375 0.71108214 0.7524921
  0.92011694 0.21459899 0.79536519 0.33614684]
 [0.03178879 0.98432867 0.78457856 0.20977375 0.66030369 0.61180689
  0.3885152  0.85280777 0.21316071 0.85504566]
 [0.48996356 0.30393229 0.18583555 0.84429114 0.66271768 0.31880202
  0.69952625 0.72408571 0.03519755 0.49215039]
 [0.12973658 0.67593

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr=np.random.rand(30)
mean_value=np.mean(arr)
print("Mean_value=",mean_value)
print(arr)

Mean_value= 0.5087813545851214
[0.76887393 0.21988681 0.50306768 0.7039107  0.045268   0.17957184
 0.33448735 0.73608193 0.21176108 0.43302486 0.29493046 0.97044088
 0.33140364 0.87675165 0.16885283 0.34001206 0.40869485 0.61196779
 0.46595741 0.83592227 0.6103261  0.82259474 0.20514254 0.95453353
 0.36727422 0.47048119 0.94046388 0.85765375 0.22810951 0.36599313]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr=np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
existing_array = np.ones((3, 3))

bordered_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
#0 * np.nan → nan
# np.nan == np.nan → False
# np.inf > np.nan → False
# np.nan - np.nan → nan
# np.nan in set([np.nan]) → True
# 0.3 == 3 * 0.1 → False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.zeros((5, 5))

for i in range(1, 5):
    matrix[i, i-1] = i

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
checkerboard_pattern =(np.indices((8,8)).sum(axis=0)% 2)
print(checkerboard_pattern)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:

shape = (6, 7, 8)

index = 100

x = index // (shape[1] * shape[2])
y = (index % (shape[1] * shape[2])) // shape[2]
z = index % shape[2]

(x, y, z)


(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
pattern = np.array([[0, 1],
                    [1, 0]])
checkerboard = np.tile(pattern, (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr=np.random.rand(5,5)
mean=np.mean(arr)
std=np.std(arr)
normalized_matrix=(arr-mean)/std
print(normalized_matrix)

[[-0.73886192  1.4572989  -1.48880263  0.35845325 -1.07296296]
 [-1.50338732  0.19998617 -1.08901356  1.47935149 -0.05896404]
 [-1.06972882 -0.65590628  1.30650502 -1.14847906 -0.74975726]
 [ 0.86082556  0.75803822  0.88474407 -0.18001228  1.08703978]
 [ 0.29938149 -1.03551013 -0.45757844  1.4194331   1.13790764]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8),
    ('blue', np.uint8),
    ('alpha', np.uint8)
])
colors = np.array([(255, 0, 0, 255),
                   (0, 255, 0, 128),
                   (0, 0, 255, 64)],
                 dtype=color_dtype)

print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255,  64)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1=np.random.rand(5,3)
matrix2=np.random.rand(3,2)
real_matrix_product=np.dot(matrix1,matrix2)
print(real_matrix_product)

[[0.82948835 0.62370879]
 [0.93281215 0.73994952]
 [0.24782055 0.16566131]
 [0.58309664 0.41121705]
 [1.13393356 0.8422353 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
matrix=np.arange(1,11)
matrix[(matrix>=3) & (matrix<=8)]*=-1
print(matrix)

[ 1  2 -1 -1 -1 -1 -1 -1  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# print(sum(range(5), -1)) using Python's built-in sum: Output is 9.
# print(sum(range(5), -1)) using NumPy's sum: Output is 10.!

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# Legal Expressions:
# Z**Z
# 2 << Z >> 2
# 1j*Z
# Z/1/1
# Illegal Expression:
# Z <- Z (This is not legal in Python and will cause a syntax error).

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# nan
# 0
# array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:

rr = np.array([-1.5, -2.3, 2.3, 1.5, 0.2, -0.2])

# Round away from zero
rounded = np.copysign(np.ceil(np.abs(arr)), arr)

print(rounded)


[4. 1. 7. 3. 1. 8. 3. 3. 4. 2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
#  How to find common values between two arrays?
arr1=np.array((1,2,3,4,5))
arr2=np.array((3,4,5,6,7))
comman=np.intersect1d(arr1,arr2)
print(comman)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# . How to ignore all numpy warnings (not recommended)?

import numpy as np
import warnings

# Suppress all warnings
warnings.filterwarnings('ignore', category=Warning)

# Example of a NumPy operation that might trigger a warning
array1 = np.array([1, 2, 3])
array2 = np.array([0, 0, 0])
result = array1 / array2  # This will trigger a divide-by-zero warning

print(result)

[inf inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# false

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
from datetime import datetime,timedelta
today=datetime.now()
yesterday=today-timedelta(days=1)
tomorrow=today+timedelta(days=1)
print("Yesterday=",yesterday)
print("Today=",today)
print("Tomorrow=",tomorrow)

Yesterday= 2024-08-27 22:36:04.517245
Today= 2024-08-28 22:36:04.517245
Tomorrow= 2024-08-29 22:36:04.517245


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
from datetime import datetime,timedelta
start_date=datetime(2016,7,1)
last_date=datetime(2016,7,31)
currentdate=start_date
while (currentdate<=last_date):
    print(currentdate)
    currentdate+=timedelta(days=1)


2016-07-01 00:00:00
2016-07-02 00:00:00
2016-07-03 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-09 00:00:00
2016-07-10 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-16 00:00:00
2016-07-17 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-23 00:00:00
2016-07-24 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-07-30 00:00:00
2016-07-31 00:00:00


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[ -2.5  -7.  -13.5]


,#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:


# Create a random array of positive numbers
random_array = np.random.rand(5) * 10  # Example array with values between 0 and 10

# Method 1: Using np.floor
integer_part_floor = np.floor(random_array)

# Method 2: Using np.trunc
integer_part_trunc = np.trunc(random_array)

# Method 3: Using np.astype(int)
integer_part_astype = random_array.astype(int)

# Method 4: Using np.fix
integer_part_fix = np.fix(random_array)

# Print the results2q
print("Original array:", random_array)
print("Integer part using np.floor:", integer_part_floor)
print("Integer part using np.trunc:", integer_part_trunc)
print("Integer part using np.astype(int):", integer_part_astype)
print("Integer part using np.fix:", integer_part_fix)


Original array: [5.7927106  3.63900278 2.64508201 3.66169916 6.83938389]
Integer part using np.floor: [5. 3. 2. 3. 6.]
Integer part using np.trunc: [5. 3. 2. 3. 6.]
Integer part using np.astype(int): [5 3 2 3 6]
Integer part using np.fix: [5. 3. 2. 3. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr=np.zeros((5,5))
arr+=np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [4]:
array=np.random.rand(10)
print(array)

[0.45356982 0.0835222  0.17291784 0.1425604  0.2727999  0.83541129
 0.92683192 0.2152172  0.42187948 0.14791761]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [3]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr=np.random.rand(10)
sorted_arr=np.sort(arr)
print(sorted_arr)

[0.02177049 0.14357306 0.17273156 0.20718169 0.3275182  0.33986667
 0.36834237 0.88622056 0.90923159 0.96268716]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [5]:
array=np.array([1,2,3,4,5])
sum=sum(array)
print(sum)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [6]:
A=np.random.rand(5)
B=np.random.rand(5)
equal=np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [8]:
array = np.array([1, 2, 3, 4, 5])
array.flags.writeable = False
try:
    array[0] = 10
except ValueError as e:
    print("Error:", e)

Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [9]:
cartesian_coords = np.random.rand(10, 2)

x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coords = np.column_stack((r, theta))

print("Cartesian coordinates:\n", cartesian_coords)
print("\nPolar coordinates (r, theta):\n", polar_coords)

Cartesian coordinates:
 [[0.30166204 0.76627077]
 [0.06431893 0.78901775]
 [0.15043542 0.05168778]
 [0.32394169 0.30513792]
 [0.63197113 0.24985609]
 [0.59590501 0.01279347]
 [0.79525855 0.29937088]
 [0.92981377 0.61503924]
 [0.95303299 0.91161315]
 [0.79302467 0.7986674 ]]

Polar coordinates (r, theta):
 [[0.82351131 1.19575396]
 [0.79163497 1.48945845]
 [0.15906742 0.33095103]
 [0.44502513 0.75551614]
 [0.67957014 0.37649997]
 [0.59604233 0.02146568]
 [0.8497406  0.36003667]
 [1.11482147 0.58439278]
 [1.31882919 0.76318857]
 [1.12550333 0.78894326]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [10]:
vector=np.random.rand(10)
max_value=np.max(vector)
vector[vector==max_value]=0
print(vector)

[0.32335317 0.61250249 0.49878731 0.77670099 0.52214213 0.16125375
 0.93700988 0.         0.33861177 0.73816444]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [12]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
xx, yy = np.meshgrid(x, y)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [13]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
C = 1.0 / (X[:, np.newaxis] - Y)
print(C)


[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [11]:

for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: Min={info.min}, Max={info.max}")

int8: Min=-128, Max=127
int16: Min=-32768, Max=32767
int32: Min=-2147483648, Max=2147483647
int64: Min=-9223372036854775808, Max=9223372036854775807


#### 49. How to print all the values of an array? (★★☆)

In [15]:
array = np.arange(1000)

print(np.array2string(array, threshold=np.inf))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [16]:
vector = np.array([1, 3, 7, 10, 15])
scalar = 8
index = np.abs(vector - scalar).argmin()
closest_value = vector[index]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest value:", closest_value)

Vector: [ 1  3  7 10 15]
Scalar: 8
Closest value: 7


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [17]:
dtype = np.dtype([('position', [('x', float), ('y', float)]),
                  ('color', [('r', float), ('g', float), ('b', float)])])

structured_array = np.array([((1.0, 2.0), (255, 0, 0)),
                             ((4.5, 5.5), (0, 255, 0)),
                             ((7.0, 8.0), (0, 0, 255))],
                            dtype=dtype)

print(structured_array)

[((1. , 2. ), (255.,   0.,   0.)) ((4.5, 5.5), (  0., 255.,   0.))
 ((7. , 8. ), (  0.,   0., 255.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [18]:
from scipy.spatial.distance import cdist

points = np.random.rand(100, 2)

distances = cdist(points, points)

print("Distances between points:\n", distances)

Distances between points:
 [[0.         0.39782717 0.81950889 ... 0.67479688 0.4560322  0.70568916]
 [0.39782717 0.         0.59669575 ... 0.85607931 0.09624087 0.64850724]
 [0.81950889 0.59669575 0.         ... 0.7514084  0.50317971 0.30913955]
 ...
 [0.67479688 0.85607931 0.7514084  ... 0.         0.83081951 0.44645976]
 [0.4560322  0.09624087 0.50317971 ... 0.83081951 0.         0.57918603]
 [0.70568916 0.64850724 0.30913955 ... 0.44645976 0.57918603 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [20]:

float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)
int_array = float_array.astype(np.int32, copy=False)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [22]:
array = np.array([[10, 20, 30],
                  [40, 50, 60]])


for index, value in np.ndenumerate(array):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 10
Index: (0, 1), Value: 20
Index: (0, 2), Value: 30
Index: (1, 0), Value: 40
Index: (1, 1), Value: 50
Index: (1, 2), Value: 60


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [23]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [25]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.03072534  0.26726729  0.04420952  0.33432832 -0.12440547 -0.14177743
   0.02828844  0.14345502 -0.22189496 -0.36019605]
 [-0.41883734  0.49046558 -0.17248604 -0.13226652 -0.09790966  0.12972097
   0.15207316  0.03102863  0.3879394  -0.36972819]
 [-0.13053601  0.00333141 -0.51162685  0.20783963 -0.05290802 -0.4040305
   0.2781753   0.27699242  0.0493952   0.28336742]
 [ 0.18558558 -0.27261848 -0.29535812  0.12844393 -0.05937421 -0.34080685
   0.06951936 -0.23582334  0.50842189  0.31201024]
 [-0.04359475 -0.13843456 -0.26446711  0.55778279 -0.13076202 -0.05836131
  -0.37182477 -0.04588848  0.17366804  0.32188216]]


#### 59. How to sort an array by the nth column? (★★☆)

In [26]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 5 6]
 [7 0 1]
 [2 3 2]]
[[7 0 1]
 [2 3 2]
 [2 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [27]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

True
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [28]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4762402762081971


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [30]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4],
                   [5],
                   [6]])
sum=0
for x, y in np.nditer([array1, array2]):
    sum+=x+y
print(sum)

63


#### 63. Create an array class that has a name attribute (★★☆)

In [42]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="Unnamed"):

        obj = np.asarray(input_array).view(cls)

        obj.name = name
        return obj

    def __init__(self, input_array, name="Unnamed"):

        pass

    def __repr__(self):
        return f"NamedArray(name={self.name}, shape={self.shape}, dtype={self.dtype})\n{super().__repr__()}"

data = np.array([[1, 2, 3], [4, 5, 6]])
named_array = NamedArray(data, name="MyArray")

print(named_array)
print("Name:", named_array.name)

[[1 2 3]
 [4 5 6]]
Name: MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [44]:
A = np.ones(10)
I = np.random.randint(0,len(A),20)
A += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(A, I, 1)
print(A)


[0 1 2 3 4 5 6 7 8 9]
[3. 3. 9. 5. 7. 3. 3. 9. 7. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [45]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [46]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [47]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[47 46 40 48]
 [49 47 50 32]
 [39 63 54 44]]
[[47 46 40 48]
 [49 47 50 32]
 [39 63 54 44]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [48]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.43766914 0.543101   0.5755223  0.48559085 0.42387603 0.59021991
 0.45679948 0.2579162  0.34884862 0.6620424 ]
0    0.437669
1    0.543101
2    0.575522
3    0.485591
4    0.423876
5    0.590220
6    0.456799
7    0.257916
8    0.348849
9    0.662042
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [49]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)

np.einsum("ij,ji->i", A, B)

array([1.24676298, 2.21159242, 1.35233639, 2.60116893, 1.19640416])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [50]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [51]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [52]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [53]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 87) ( 2, 99) ( 3, 28) ( 3, 62) ( 4, 31) ( 4, 60) ( 5, 70) ( 5, 72)
 ( 7, 51) ( 7, 85) (11, 24) (11, 46) (24, 46) (24, 54) (24, 90) (28, 32)
 (28, 62) (28, 90) (29, 45) (29, 81) (31, 60) (32, 90) (33, 46) (33, 92)
 (45, 81) (46, 92) (51, 85) (54, 90) (70, 72) (87, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [54]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [55]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [56]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [57]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.86654454,  0.32288158,  0.77027771, -0.10338562,  0.15961016,
        0.80976528,  0.46104553, -0.79853939,  0.81498331,  0.62473744,
        0.78664397, -0.97308537,  0.49353614,  0.45108112, -0.35721106,
       -0.84954126,  0.12468908, -0.67057535,  0.04988277,  0.31734482,
        0.18740731, -0.38886828, -0.51210834, -0.43846776, -0.01501555,
       -0.63530796, -0.29986443, -0.41287115, -0.27149971, -0.45897217,
       -0.48670168, -0.54630329,  0.83480229, -0.9463294 , -0.83353412,
       -0.70722125, -0.67308668, -0.66090227, -0.6719807 ,  0.68360382,
        0.92317696,  0.37623258, -0.72695649, -0.24200643,  0.33368995,
       -0.90447775, -0.17326957, -0.95356641, -0.611707  ,  0.00902373,
        0.270666  , -0.37731833,  0.79555663,  0.28420065,  0.38563845,
       -0.83887435,  0.81680366,  0.99914159, -0.08660897, -0.0086151 ,
        0.05608254,  0.59199248, -0.83465086,  0.87395767, -0.78570454,
       -0.38150895,  0.97457737, -0.06308986, -0.71162687,  0.52

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [58]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[12.81200378  1.13738257 16.78467763  6.39178754  0.15322973  5.27034038
  7.03935335  2.15130034 14.86785751  5.88530044]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [59]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.65151093  4.21149077  1.35054766  2.48147993  5.51418786  0.95900207
   2.74437359  7.82615042  6.68123069  1.6820999 ]
 [ 3.58601762 12.48066979  2.15789391  1.41014129 10.26613921 13.53417495
  14.01322203  0.22880859  2.7651443   4.68324641]
 [ 8.43525066  9.54867267  7.73444977  1.51403578  1.16380706  6.59326088
   4.82267172  5.45430808 14.13406561  8.69059719]
 [ 4.79632319  8.63338443  6.04082493  7.87197445  1.92617849  5.67623437
   5.84901181  4.76266525  5.63698796  3.76824775]
 [ 0.79710586 10.8431456   2.17149483  4.99670245  5.89315218  9.62602015
   9.90569331  2.66189564  1.51841923  0.29236936]
 [ 5.80775715  5.68884559  5.46436056  0.96128268  1.36513044  2.70640573
   1.11799252  5.02851728 10.72092275  5.83997416]
 [ 7.86819978  5.47687887  7.61046515  3.19208355  0.72209161  4.01689137
   2.62510688  2.93333475 12.44622462  7.82953844]
 [ 0.46676532  1.95187213  0.82668275  0.27623447  6.5123801   5.08440459
   6.32402001  4.31695695  3.84320646  0.06100219]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [60]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

print(Z)
print(R)

[[2 9 9 0 4 3 6 1 6 0]
 [2 6 9 2 1 7 4 4 3 4]
 [0 3 9 1 0 4 2 3 6 3]
 [1 7 1 6 5 8 9 1 0 9]
 [6 0 4 4 0 5 3 9 6 1]
 [9 8 6 7 2 0 1 7 0 5]
 [2 5 4 7 4 5 5 3 0 2]
 [9 3 9 9 4 4 9 2 1 7]
 [7 0 9 0 7 2 3 8 7 0]
 [8 9 3 4 5 0 8 2 7 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [61]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [62]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [63]:
frequent = np.linalg.matrix_rank(Z)
print(frequent)

10


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [64]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[4 0 0]
   [3 4 4]
   [4 3 1]]

  [[0 0 3]
   [4 4 3]
   [3 1 1]]

  [[0 3 0]
   [4 3 4]
   [1 1 3]]

  [[3 0 2]
   [3 4 1]
   [1 3 0]]

  [[0 2 0]
   [4 1 1]
   [3 0 2]]

  [[2 0 3]
   [1 1 2]
   [0 2 1]]

  [[0 3 3]
   [1 2 1]
   [2 1 4]]

  [[3 3 2]
   [2 1 2]
   [1 4 0]]]


 [[[3 4 4]
   [4 3 1]
   [4 0 1]]

  [[4 4 3]
   [3 1 1]
   [0 1 0]]

  [[4 3 4]
   [1 1 3]
   [1 0 4]]

  [[3 4 1]
   [1 3 0]
   [0 4 0]]

  [[4 1 1]
   [3 0 2]
   [4 0 1]]

  [[1 1 2]
   [0 2 1]
   [0 1 2]]

  [[1 2 1]
   [2 1 4]
   [1 2 0]]

  [[2 1 2]
   [1 4 0]
   [2 0 2]]]


 [[[4 3 1]
   [4 0 1]
   [3 1 1]]

  [[3 1 1]
   [0 1 0]
   [1 1 2]]

  [[1 1 3]
   [1 0 4]
   [1 2 3]]

  [[1 3 0]
   [0 4 0]
   [2 3 3]]

  [[3 0 2]
   [4 0 1]
   [3 3 1]]

  [[0 2 1]
   [0 1 2]
   [3 1 0]]

  [[2 1 4]
   [1 2 0]
   [1 0 1]]

  [[1 4 0]
   [2 0 2]
   [0 1 2]]]


 [[[4 0 1]
   [3 1 1]
   [3 0 4]]

  [[0 1 0]
   [1 1 2]
   [0 4 0]]

  [[1 0 4]
   [1 2 3]
   [4 0 4]]

  [[0 4 0]
   [2 3 3]
   [0 4 1]]

  [[4 0 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [65]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2 10 14  9 10]
 [10  5  5 11  6]
 [14  5  2 42 14]
 [ 9 11 42  8 10]
 [10  6 14 10  4]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [66]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [67]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [68]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [69]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9999 9997 9996 9998]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-69-824d05997b6f>, line 9)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [70]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [71]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [75]:
Z = np.random.rand(1000000)
Z_power_1 = Z ** 3

Z_power_2 = np.power(Z, 3)

Z_power_3 = np.multiply(np.multiply(Z, Z), Z)

assert np.allclose(Z_power_1, Z_power_2)
assert np.allclose(Z_power_1, Z_power_3)

print("Computation completed successfully.")



Computation completed successfully.


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [76]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [77]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 2 2]
 [0 4 0]
 [3 2 4]
 [2 4 3]
 [4 4 1]
 [3 0 2]
 [4 3 1]
 [4 1 3]
 [4 4 0]
 [1 3 1]]
[[3 2 2]
 [0 4 0]
 [3 2 4]
 [2 4 3]
 [4 4 1]
 [3 0 2]
 [4 3 1]
 [4 1 3]
 [4 4 0]
 [1 3 1]]
[[3 2 2]
 [0 4 0]
 [3 2 4]
 [2 4 3]
 [4 4 1]
 [3 0 2]
 [4 3 1]
 [4 1 3]
 [4 4 0]
 [1 3 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [78]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [79]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 1]]
[[0 0 0]
 [0 1 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [84]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.46007053, 0.56165943, 0.14765577, 0.60683754, 0.82002439,
        0.05465215, 0.09549165, 0.29921783, 0.90511107, 0.16641426],
       [0.01553836, 0.01896941, 0.00498691, 0.02049525, 0.0276954 ,
        0.00184581, 0.00322512, 0.01010574, 0.03056911, 0.00562045],
       [0.26675296, 0.32565511, 0.08561212, 0.35184978, 0.4754574 ,
        0.0316878 , 0.05536691, 0.17348915, 0.52479141, 0.09648846],
       [0.35848534, 0.43764306, 0.11505286, 0.47284569, 0.63896013,
        0.04258476, 0.07440676, 0.23314949, 0.70525938, 0.12966941],
       [0.30080417, 0.36722521, 0.09654057, 0.39676365, 0.53614987,
        0.03573277, 0.06243453, 0.19563516, 0.5917814 , 0.10880528],
       [0.43506508, 0.53113249, 0.13963048, 0.57385512, 0.77545497,
        0.05168173, 0.09030156, 0.28295494, 0.85591708, 0.15736942],
       [0.29040908, 0.35453477, 0.09320435, 0.38305242, 0.51762178,
        0.03449793, 0.06027694, 0.18887446, 0.57133082, 0.10504522],
       [0.3685652 , 0.44994867, 0.1182879

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [85]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [82]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [83]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.24054732  0.15406604]
